/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the vehicles domain.
 * Use these factories in tests to create test data.
 */

export { createCreatePullRequest } from "./pull/dto/create-pull.dto.factory.js";
export { createVehicle } from "./vehicle/entity/vehicle.entity.factory.js";
export { createYieldForesight } from "./yield-foresight/entity/yield-foresight.entity.factory.js";
