/**
 * ListAvailability DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAvailabilityWindowsParams } from "@peerwheel/core/vehicles";

export function createListAvailabilityRequest(overrides: Partial<ListAvailabilityWindowsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
