/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAttestationsDomainModule,
  buildCanvasDomainModule,
  buildCorridorsDomainModule,
  buildDisputesDomainModule,
  buildIdentityDomainModule,
  buildRidesDomainModule,
  buildSettlementsDomainModule,
  buildVehiclesDomainModule,
} from "../domains/index.js";
import type {
  AttestationsDomainModule,
  CanvasDomainModule,
  CorridorsDomainModule,
  DisputesDomainModule,
  IdentityDomainModule,
  RidesDomainModule,
  SettlementsDomainModule,
  VehiclesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private attestationsModule: AttestationsDomainModule | null = null;
  private canvasModule: CanvasDomainModule | null = null;
  private corridorsModule: CorridorsDomainModule | null = null;
  private disputesModule: DisputesDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private ridesModule: RidesDomainModule | null = null;
  private settlementsModule: SettlementsDomainModule | null = null;
  private vehiclesModule: VehiclesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get attestations domain module
   */
  getAttestationsDependencies(): AttestationsDomainModule {
    if (!this.attestationsModule) {
      this.attestationsModule = buildAttestationsDomainModule(this.dynamoClient);
    }
    return this.attestationsModule;
  }

  /**
   * Get canvas domain module
   */
  getCanvasDependencies(): CanvasDomainModule {
    if (!this.canvasModule) {
      this.canvasModule = buildCanvasDomainModule(this.dynamoClient);
    }
    return this.canvasModule;
  }

  /**
   * Get corridors domain module
   */
  getCorridorsDependencies(): CorridorsDomainModule {
    if (!this.corridorsModule) {
      this.corridorsModule = buildCorridorsDomainModule(this.dynamoClient);
    }
    return this.corridorsModule;
  }

  /**
   * Get disputes domain module
   */
  getDisputesDependencies(): DisputesDomainModule {
    if (!this.disputesModule) {
      this.disputesModule = buildDisputesDomainModule(this.dynamoClient);
    }
    return this.disputesModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get rides domain module
   */
  getRidesDependencies(): RidesDomainModule {
    if (!this.ridesModule) {
      this.ridesModule = buildRidesDomainModule(this.dynamoClient);
    }
    return this.ridesModule;
  }

  /**
   * Get settlements domain module
   */
  getSettlementsDependencies(): SettlementsDomainModule {
    if (!this.settlementsModule) {
      this.settlementsModule = buildSettlementsDomainModule(this.dynamoClient);
    }
    return this.settlementsModule;
  }

  /**
   * Get vehicles domain module
   */
  getVehiclesDependencies(): VehiclesDomainModule {
    if (!this.vehiclesModule) {
      this.vehiclesModule = buildVehiclesDomainModule(this.dynamoClient);
    }
    return this.vehiclesModule;
  }

  clearAttestationsDependencies(): void { this.attestationsModule = null; }
  clearCanvasDependencies(): void { this.canvasModule = null; }
  clearCorridorsDependencies(): void { this.corridorsModule = null; }
  clearDisputesDependencies(): void { this.disputesModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearRidesDependencies(): void { this.ridesModule = null; }
  clearSettlementsDependencies(): void { this.settlementsModule = null; }
  clearVehiclesDependencies(): void { this.vehiclesModule = null; }

  getAttestationsDependenciesForRequest(): AttestationsDomainModule {
    return this.getAttestationsDependencies();
  }

  getCanvasDependenciesForRequest(): CanvasDomainModule {
    return this.getCanvasDependencies();
  }

  getCorridorsDependenciesForRequest(): CorridorsDomainModule {
    return this.getCorridorsDependencies();
  }

  getDisputesDependenciesForRequest(): DisputesDomainModule {
    return this.getDisputesDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getRidesDependenciesForRequest(): RidesDomainModule {
    return this.getRidesDependencies();
  }

  getSettlementsDependenciesForRequest(): SettlementsDomainModule {
    return this.getSettlementsDependencies();
  }

  getVehiclesDependenciesForRequest(): VehiclesDomainModule {
    return this.getVehiclesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.attestationsModule = null;
    this.canvasModule = null;
    this.corridorsModule = null;
    this.disputesModule = null;
    this.identityModule = null;
    this.ridesModule = null;
    this.settlementsModule = null;
    this.vehiclesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
