/**
 * ListVehicles handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listVehicles } from "@peerwheel/api-server/domains/vehicles/handlers";
import type { VehiclesDDDDependencies } from "@peerwheel/api-server/domains/vehicles";
import { createVehicle as createVehicleEntity } from "@peerwheel/factories/vehicles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { VEHICLES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListVehicles", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VehiclesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VehiclesDDDDependencies>(
      VEHICLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createVehicleEntity({ orgId }),
      createVehicleEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListVehicles, "execute").mockResolvedValue(useCaseResult);

    await listVehicles(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListVehicles.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
