/**
 * FitRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FitRepository Port
 *
 * DDD: Application port for fitrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCanvasFitInput, GetCanvasFitOutput, UpdateCanvasFitInput, UpdateCanvasFitOutput } from "../dto/fit.dto";
export interface FitRepository {
  getCanvasFit(input: GetCanvasFitInput): Promise<GetCanvasFitOutput>;
  updateCanvasFit(input: UpdateCanvasFitInput): Promise<UpdateCanvasFitOutput>;
}

export type { GetCanvasFitInput, GetCanvasFitOutput, UpdateCanvasFitInput, UpdateCanvasFitOutput } from "../dto/fit.dto";
