/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the attestations domain.
 * Use these factories in tests to create test data.
 */

export { createCreateClearHoldRequest } from "./clear-hold/dto/create-clear-hold.dto.factory.js";
export { createCreateKeepHoldRequest } from "./keep-hold/dto/create-keep-hold.dto.factory.js";
