/**
 * MatchRide handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { matchRide } from "@peerwheel/api-server/domains/rides/handlers";
import type { RidesDDDDependencies } from "@peerwheel/api-server/domains/rides";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { RIDES_USE_CASES } from "../__factories__/use-cases.js";

describe("MatchRide", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RidesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RidesDDDDependencies>(
      RIDES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeMatchRide, "execute").mockResolvedValue(useCaseResult);

    await matchRide(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeMatchRide.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
