/**
 * AvailabilityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AvailabilityRepository Port
 *
 * DDD: Application port for availabilityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAvailabilityWindowsInput, ListAvailabilityWindowsOutput } from "../dto/availability.dto";
export interface AvailabilityRepository {
  listAvailabilityWindows(input: ListAvailabilityWindowsInput): Promise<ListAvailabilityWindowsOutput>;
}

export type { ListAvailabilityWindowsInput, ListAvailabilityWindowsOutput } from "../dto/availability.dto";
