/**
 * AvailabilityPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AvailabilityPublisher Port
 *
 * DDD: Application port for availabilitypublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishAvailabilityInput, PublishAvailabilityOutput } from "../dto/availability.dto";
export interface AvailabilityPublisher {
  publishAvailability(input: PublishAvailabilityInput): Promise<PublishAvailabilityOutput>;
}

export type { PublishAvailabilityInput, PublishAvailabilityOutput } from "../dto/availability.dto";
