/**
 * PullRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PullRepository Port
 *
 * DDD: Application port for pullrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PullAvailabilityInput, PullAvailabilityOutput } from "../dto/pull.dto";
export interface PullRepository {
  pullAvailability(input: PullAvailabilityInput): Promise<PullAvailabilityOutput>;
}

export type { PullAvailabilityInput, PullAvailabilityOutput } from "../dto/pull.dto";
