/**
 * VehicleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VehicleRepository Port
 *
 * DDD: Application port for vehiclerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetVehicleInput, GetVehicleOutput, ListVehiclesInput, ListVehiclesOutput, RegisterVehicleInput, RegisterVehicleOutput, UpdateVehicleInput, UpdateVehicleOutput } from "../dto/vehicle.dto";
export interface VehicleRepository {
  listVehicles(input: ListVehiclesInput): Promise<ListVehiclesOutput>;
  registerVehicle(input: RegisterVehicleInput): Promise<RegisterVehicleOutput>;
  getVehicle(input: GetVehicleInput): Promise<GetVehicleOutput>;
  updateVehicle(input: UpdateVehicleInput): Promise<UpdateVehicleOutput>;
}

export type { GetVehicleInput, GetVehicleOutput, ListVehiclesInput, ListVehiclesOutput, RegisterVehicleInput, RegisterVehicleOutput, UpdateVehicleInput, UpdateVehicleOutput } from "../dto/vehicle.dto";
