/**
 * YieldForesightRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * YieldForesightRepository Port
 *
 * DDD: Application port for yieldforesightrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetYieldForesightInput, GetYieldForesightOutput } from "../dto/yield-foresight.dto";
export interface YieldForesightRepository {
  getYieldForesight(input: GetYieldForesightInput): Promise<GetYieldForesightOutput>;
}

export type { GetYieldForesightInput, GetYieldForesightOutput } from "../dto/yield-foresight.dto";
