/**
 * ExecuteRefuseRide - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRefuseRide Use Case
 *
 * DDD: Application use case for get Refuse.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RefuseRideInput, RefuseRideOutput } from "../dto/refuse.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { RefuseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRefuseRide {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly refuse: RefuseRepository
  ) {}

  async execute(input: RefuseRideInput): Promise<RefuseRideOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ridId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).rideId) {
      throw new ValidationError("rideId is required");
    }
    const rideId = (input as any).rideId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.refuse.refuseRide({ rideId: rideId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${rideId}`);
    }

    return entity as RefuseRideOutput;
  }
}
