/**
 * ExecuteListRides - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRides Use Case
 *
 * DDD: Application use case for list Ride.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRidesInput, ListRidesOutput } from "../dto/ride.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { RideRepository } from "../ports";

export class ExecuteListRides {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ride: RideRepository
  ) {}

  async execute(input: ListRidesInput): Promise<ListRidesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ridId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ride.listRides({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRidesOutput;
  }
}
