/**
 * ExecuteCompleteRide - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCompleteRide Use Case
 *
 * DDD: Application use case for create Complete.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CompleteRideInput, CompleteRideOutput } from "../dto/complete.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { CompleteRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCompleteRide {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complete: CompleteRepository
  ) {}

  async execute(input: CompleteRideInput): Promise<CompleteRideOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ridId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (rides domain)
    const entityId = this.idGenerator.ridId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.complete.completeRide({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CompleteRideOutput;
  }
}
