/**
 * Routes for Availability
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listAvailabilityWindows, publishAvailability } from "../handlers/availability.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function availabilityRoutes(fastify: FastifyInstance) {
  // GET /v1/vehicles/{vehicleId}/availability (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vehicles/:vehicleId/availability",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await listAvailabilityWindows(request, reply, deps);
      });
    }
  );


  // POST /v1/vehicles/{vehicleId}/availability (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/vehicles/:vehicleId/availability",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await publishAvailability(request, reply, deps);
      });
    }
  );


}
