/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { availabilityRoutes } from "./availability.routes.js";
export { vehicleRoutes } from "./vehicle.routes.js";
export { yieldForesightRoutes } from "./yield-foresight.routes.js";
export { pullRoutes } from "./pull.routes.js";
