/**
 * Routes for Vehicle
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getVehicle, listVehicles, registerVehicle, updateVehicle } from "../handlers/vehicle.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vehicleRoutes(fastify: FastifyInstance) {
  // GET /v1/vehicles (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vehicles",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await listVehicles(request, reply, deps);
      });
    }
  );


  // POST /v1/vehicles (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/vehicles",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await registerVehicle(request, reply, deps);
      });
    }
  );


  // GET /v1/vehicles/{vehicleId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vehicles/:vehicleId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await getVehicle(request, reply, deps);
      });
    }
  );


  // PATCH /v1/vehicles/{vehicleId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/vehicles/:vehicleId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVehiclesDependenciesForRequest();
        await updateVehicle(request, reply, deps);
      });
    }
  );


}
