/**
 * CompleteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompleteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CompleteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CompleteRepository,
} from "@peerwheel/services/rides";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CompleteRepositoryDdb } from "./complete-repository.ddb.js";

/**
 * CompleteRepositoryAdapter
 *
 * Implements CompleteRepository port for infrastructure layer.
 */
export class CompleteRepositoryAdapter implements CompleteRepository {
  private readonly ddb: CompleteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CompleteRepositoryDdb(this.dynamoClient);
  }

  async completeRide(input: Parameters<CompleteRepository['completeRide']>[0]): Promise<Awaited<ReturnType<CompleteRepository['completeRide']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.completeRide(input);
  }
}
