/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./complete-repository.ddb.js";
export * from "./match-repository.ddb.js";
export * from "./refuse-repository.ddb.js";
export * from "./ride-repository.ddb.js";
export * from "./complete-repository.adapter.js";
export * from "./match-repository.adapter.js";
export * from "./refuse-repository.adapter.js";
export * from "./ride-repository.adapter.js";
