/**
 * RideRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RideRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RideRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RideRepository,
} from "@peerwheel/services/rides";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RideRepositoryDdb } from "./ride-repository.ddb.js";

/**
 * RideRepositoryAdapter
 *
 * Implements RideRepository port for infrastructure layer.
 */
export class RideRepositoryAdapter implements RideRepository {
  private readonly ddb: RideRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RideRepositoryDdb(this.dynamoClient);
  }

  async listRides(input: Parameters<RideRepository['listRides']>[0]): Promise<Awaited<ReturnType<RideRepository['listRides']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRides(input);
  }

  async requestRide(input: Parameters<RideRepository['requestRide']>[0]): Promise<Awaited<ReturnType<RideRepository['requestRide']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestRide(input);
  }

  async getRide(input: Parameters<RideRepository['getRide']>[0]): Promise<Awaited<ReturnType<RideRepository['getRide']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRide(input);
  }
}
