/**
 * CorridorRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorridorRepository Port
 *
 * DDD: Application port for corridorrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCorridorInput, GetCorridorOutput, ListCorridorsInput, ListCorridorsOutput } from "../dto/corridor.dto";
export interface CorridorRepository {
  listCorridors(input: ListCorridorsInput): Promise<ListCorridorsOutput>;
  getCorridor(input: GetCorridorInput): Promise<GetCorridorOutput>;
}

export type { GetCorridorInput, GetCorridorOutput, ListCorridorsInput, ListCorridorsOutput } from "../dto/corridor.dto";
