/**
 * LicensingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicensingRepository Port
 *
 * DDD: Application port for licensingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UpdateCorridorLicensingInput, UpdateCorridorLicensingOutput } from "../dto/licensing.dto";
export interface LicensingRepository {
  updateCorridorLicensing(input: UpdateCorridorLicensingInput): Promise<UpdateCorridorLicensingOutput>;
}

export type { UpdateCorridorLicensingInput, UpdateCorridorLicensingOutput } from "../dto/licensing.dto";
