/**
 * PauseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseRepository Port
 *
 * DDD: Application port for pauserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PauseCorridorInput, PauseCorridorOutput } from "../dto/pause.dto";
export interface PauseRepository {
  pauseCorridor(input: PauseCorridorInput): Promise<PauseCorridorOutput>;
}

export type { PauseCorridorInput, PauseCorridorOutput } from "../dto/pause.dto";
