/**
 * Routes for Settlement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSettlement, listSettlements } from "../handlers/settlement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function settlementRoutes(fastify: FastifyInstance) {
  // GET /v1/settlements (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementsDependenciesForRequest();
        await listSettlements(request, reply, deps);
      });
    }
  );


  // GET /v1/settlements/{settlementId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlements/:settlementId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { settlementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementsDependenciesForRequest();
        await getSettlement(request, reply, deps);
      });
    }
  );


}
