/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Canvas Domain Use Cases
 * 
 * List of all use case names for the canvas domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CANVAS_USE_CASES = [
  "executeGetCanvasFit",
  "executeUpdateCanvasFit"
] as const;
