/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { GetAttestationParams, ListAttestationsParams, SubmitIntegrityAttestationParams, SubmitIntegrityAttestationRequestInput } from "@peerwheel/core/attestations/types";

export type ListAttestationsInput = ListAttestationsParams;

export type SubmitIntegrityAttestationInput = SubmitIntegrityAttestationParams & SubmitIntegrityAttestationRequestInput;

export type GetAttestationInput = GetAttestationParams;

export type ListAttestationsOutput = {};

export type SubmitIntegrityAttestationOutput = {};

export type GetAttestationOutput = {};
