/**
 * ClearHold DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClearHold DTOs
 *
 * DDD: Application DTOs for ClearHold use cases.
 */

import type { ClearAttestationHoldParams } from "@peerwheel/core/attestations/types";

export type ClearAttestationHoldInput = ClearAttestationHoldParams;

export type ClearAttestationHoldOutput = {};
