/**
 * KeepHold DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeepHold DTOs
 *
 * DDD: Application DTOs for KeepHold use cases.
 */

import type { KeepAttestationHoldParams } from "@peerwheel/core/attestations/types";

export type KeepAttestationHoldInput = KeepAttestationHoldParams;

export type KeepAttestationHoldOutput = {};
