/**
 * Export DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Export DTOs
 *
 * DDD: Application DTOs for Export use cases.
 */

import type { ExportDisputeCasePackParams } from "@peerwheel/core/disputes/types";

export type ExportDisputeCasePackInput = ExportDisputeCasePackParams;

export type ExportDisputeCasePackOutput = {};
