/**
 * Extend DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Extend DTOs
 *
 * DDD: Application DTOs for Extend use cases.
 */

import type { ExtendDisputeParams, ExtendDisputeRequestInput } from "@peerwheel/core/disputes/types";

export type ExtendDisputeInput = ExtendDisputeParams & ExtendDisputeRequestInput;

export type ExtendDisputeOutput = {};
