/**
 * Handlers for Fit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CanvasDomainModule } from "../dependencies/canvas-ddd.dependencies.js";
import type { GetCanvasFitInput, UpdateCanvasFitInput } from "@peerwheel/services/canvas";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/canvas/fits
 * Operation: getCanvasFit
 */
export async function getCanvasFit(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CanvasDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCanvasFitInput = {};
  const result = await deps.useCases.fits.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/canvas/fits
 * Operation: updateCanvasFit
 */
export async function updateCanvasFit(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CanvasDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateCanvasFitInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.fits.update.execute(input);
  return reply.code(200).send(result);
}


