/**
 * Corridor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Corridor DTOs
 *
 * DDD: Application DTOs for Corridor use cases.
 */

import type { GetCorridorParams, ListCorridorsParams } from "@peerwheel/core/corridors/types";

export type ListCorridorsInput = ListCorridorsParams;

export type GetCorridorInput = GetCorridorParams;

export type ListCorridorsOutput = {};

export type GetCorridorOutput = {};
