/**
 * Pause DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pause DTOs
 *
 * DDD: Application DTOs for Pause use cases.
 */

import type { PauseCorridorParams, PauseCorridorRequestInput } from "@peerwheel/core/corridors/types";

export type PauseCorridorInput = PauseCorridorParams & PauseCorridorRequestInput;

export type PauseCorridorOutput = {};
