/**
 * ExecuteRegisterVehicle - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterVehicle Use Case
 *
 * DDD: Application use case for create Vehicle.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterVehicleInput, RegisterVehicleOutput } from "../dto/vehicle.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { VehicleRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterVehicle {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vehicle: VehicleRepository
  ) {}

  async execute(input: RegisterVehicleInput): Promise<RegisterVehicleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vehId();

    // All field names extracted from OpenAPI spec: corridorId, licensingTags, ownerId, sensors, telematicsEndpoint
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.ownerId) {
      throw new ValidationError("ownerId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (vehicles domain)
    const entityId = this.idGenerator.vehId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.vehicle.registerVehicle({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterVehicleOutput;
  }
}
