/**
 * ExecuteUpdateVehicle - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateVehicle Use Case
 *
 * DDD: Application use case for update Vehicle.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateVehicleInput, UpdateVehicleOutput } from "../dto/vehicle.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { VehicleRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateVehicle {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vehicle: VehicleRepository
  ) {}

  async execute(input: UpdateVehicleInput): Promise<UpdateVehicleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vehId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).vehicleId) {
      throw new ValidationError("vehicleId is required");
    }
    const vehicleId = (input as any).vehicleId;

    // Load existing entity
    const existing = await this.vehicle.getVehicle({ vehicleId: vehicleId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${vehicleId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.vehicle.updateVehicle({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateVehicleOutput;
  }
}
