/**
 * ExecuteListAvailabilityWindows - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAvailabilityWindows Use Case
 *
 * DDD: Application use case for list Availability.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAvailabilityWindowsInput, ListAvailabilityWindowsOutput } from "../dto/availability.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { AvailabilityRepository } from "../ports";

export class ExecuteListAvailabilityWindows {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly availability: AvailabilityRepository
  ) {}

  async execute(input: ListAvailabilityWindowsInput): Promise<ListAvailabilityWindowsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vehId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.availability.listAvailabilityWindows({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAvailabilityWindowsOutput;
  }
}
