/**
 * ExecuteGetYieldForesight - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetYieldForesight Use Case
 *
 * DDD: Application use case for get YieldForesight.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetYieldForesightInput, GetYieldForesightOutput } from "../dto/yield-foresight.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { YieldForesightRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetYieldForesight {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly yieldForesight: YieldForesightRepository
  ) {}

  async execute(input: GetYieldForesightInput): Promise<GetYieldForesightOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vehId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).vehicleId) {
      throw new ValidationError("vehicleId is required");
    }
    const vehicleId = (input as any).vehicleId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.yieldForesight.getYieldForesight({ vehicleId: vehicleId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${vehicleId}`);
    }

    return entity as GetYieldForesightOutput;
  }
}
