/**
 * PauseCorridor handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { pauseCorridor } from "@peerwheel/api-server/domains/corridors/handlers";
import type { CorridorsDDDDependencies } from "@peerwheel/api-server/domains/corridors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { CORRIDORS_USE_CASES } from "../__factories__/use-cases.js";

describe("PauseCorridor", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CorridorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CorridorsDDDDependencies>(
      CORRIDORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePauseCorridor, "execute").mockResolvedValue(useCaseResult);

    await pauseCorridor(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePauseCorridor.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
