/**
 * ClearHoldRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClearHoldRepository Port
 *
 * DDD: Application port for clearholdrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClearAttestationHoldInput, ClearAttestationHoldOutput } from "../dto/clear-hold.dto";
export interface ClearHoldRepository {
  clearAttestationHold(input: ClearAttestationHoldInput): Promise<ClearAttestationHoldOutput>;
}

export type { ClearAttestationHoldInput, ClearAttestationHoldOutput } from "../dto/clear-hold.dto";
