/**
 * Repository interface for Settlement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SettlementEntity
} from "../models/settlement.entity.js";
import type {
  ListSettlementsParams
} from "../types/index.js";
/**
 * SettlementRepository Interface
 */
export interface SettlementRepository extends ReadRepository<SettlementEntity, string, ListSettlementsParams> {

}
