/**
 * CreateComplete DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CompleteRideParams } from "@peerwheel/core/rides";

export function createCreateCompleteRequest(overrides: Partial<CompleteRideParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
