/**
 * Vehicle Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/vehicles.openapi.types.js";
import { schemas } from "../schemas/vehicles.schemas.js";

/**
 * Entity: VehicleEntity
 * Description: Represents the Vehicle domain model.
 * Source: schemas.Vehicle
 * Type: Domain Entity (API)
 */
export const VehicleEntitySchema = schemas.Vehicle;
export type VehicleEntity = components["schemas"]["Vehicle"];
