/**
 * YieldForesight Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/vehicles.openapi.types.js";
import { schemas } from "../schemas/vehicles.schemas.js";

/**
 * Entity: YieldForesightEntity
 * Description: Represents the YieldForesight domain model.
 * Source: schemas.YieldForesight
 * Type: Domain Entity (API)
 */
export const YieldForesightEntitySchema = schemas.YieldForesight;
export type YieldForesightEntity = components["schemas"]["YieldForesight"];
