/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the rides domain.
 * Use these factories in tests to create test data.
 */

export { createCreateCompleteRequest } from "./complete/dto/create-complete.dto.factory.js";
export { createCreateRefuseRequest } from "./refuse/dto/create-refuse.dto.factory.js";
export { createRide } from "./ride/entity/ride.entity.factory.js";
