/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as attestationsRoutes from "../../domains/attestations/routes/index.js";
import * as canvasRoutes from "../../domains/canvas/routes/index.js";
import * as corridorsRoutes from "../../domains/corridors/routes/index.js";
import * as disputesRoutes from "../../domains/disputes/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as ridesRoutes from "../../domains/rides/routes/index.js";
import * as settlementsRoutes from "../../domains/settlements/routes/index.js";
import * as vehiclesRoutes from "../../domains/vehicles/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "attestations", mod: attestationsRoutes },
  { domain: "canvas", mod: canvasRoutes },
  { domain: "corridors", mod: corridorsRoutes },
  { domain: "disputes", mod: disputesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "rides", mod: ridesRoutes },
  { domain: "settlements", mod: settlementsRoutes },
  { domain: "vehicles", mod: vehiclesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
