/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@peerwheel/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "attestations", "canvas", "corridors", "disputes", "identity", "rides", "settlements", "vehicles"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      attestations: [{ method: "GET", path: "/v1/attestations" }, { method: "POST", path: "/v1/rides/:rideId/attestations" }, { method: "GET", path: "/v1/attestations/:attestationId" }, { method: "POST", path: "/v1/attestations/:attestationId/clear-hold" }, { method: "POST", path: "/v1/attestations/:attestationId/keep-hold" }],
      canvas: [{ method: "GET", path: "/v1/canvas/fits" }, { method: "PUT", path: "/v1/canvas/fits" }],
      corridors: [{ method: "GET", path: "/v1/corridors" }, { method: "GET", path: "/v1/corridors/:corridorId" }, { method: "POST", path: "/v1/corridors/:corridorId/pause" }, { method: "POST", path: "/v1/corridors/:corridorId/resume" }, { method: "PUT", path: "/v1/corridors/:corridorId/licensing" }],
      disputes: [{ method: "GET", path: "/v1/disputes" }, { method: "POST", path: "/v1/disputes" }, { method: "GET", path: "/v1/disputes/:disputeId" }, { method: "POST", path: "/v1/disputes/:disputeId/resolve" }, { method: "POST", path: "/v1/disputes/:disputeId/extend" }, { method: "POST", path: "/v1/disputes/:disputeId/export" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      rides: [{ method: "GET", path: "/v1/rides" }, { method: "POST", path: "/v1/rides" }, { method: "GET", path: "/v1/rides/:rideId" }, { method: "POST", path: "/v1/rides/:rideId/match" }, { method: "POST", path: "/v1/rides/:rideId/complete" }, { method: "POST", path: "/v1/rides/:rideId/refuse" }],
      settlements: [{ method: "GET", path: "/v1/settlements" }, { method: "GET", path: "/v1/settlements/:settlementId" }, { method: "POST", path: "/v1/settlements/:settlementId/execute" }, { method: "POST", path: "/v1/settlements/:settlementId/retry" }],
      vehicles: [{ method: "GET", path: "/v1/vehicles" }, { method: "POST", path: "/v1/vehicles" }, { method: "GET", path: "/v1/vehicles/:vehicleId" }, { method: "PATCH", path: "/v1/vehicles/:vehicleId" }, { method: "GET", path: "/v1/vehicles/:vehicleId/availability" }, { method: "POST", path: "/v1/vehicles/:vehicleId/availability" }, { method: "POST", path: "/v1/vehicles/:vehicleId/availability/:availabilityWindowId/pull" }, { method: "GET", path: "/v1/vehicles/:vehicleId/yield-foresight" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
