/**
 * Settlement Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/settlements.openapi.types.js";
import { schemas } from "../schemas/settlements.schemas.js";

/**
 * Entity: SettlementEntity
 * Description: Represents the Settlement domain model.
 * Source: schemas.Settlement
 * Type: Domain Entity (API)
 */
export const SettlementEntitySchema = schemas.Settlement;
export type SettlementEntity = components["schemas"]["Settlement"];
