/**
 * ExecuteGetDispute - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDispute Use Case
 *
 * DDD: Application use case for get Dispute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDisputeInput, GetDisputeOutput } from "../dto/dispute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { DisputeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDispute {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dispute: DisputeRepository
  ) {}

  async execute(input: GetDisputeInput): Promise<GetDisputeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dspId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).disputeId) {
      throw new ValidationError("disputeId is required");
    }
    const disputeId = (input as any).disputeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dispute.getDispute({ disputeId: disputeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${disputeId}`);
    }

    return entity as GetDisputeOutput;
  }
}
