/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Disputes Domain Use Cases
 * 
 * List of all use case names for the disputes domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DISPUTES_USE_CASES = [
  "executeExportDisputeCasePack",
  "executeExtendDispute",
  "executeGetDispute",
  "executeListDisputes",
  "executeOpenDispute",
  "executeResolveDispute"
] as const;
