/**
 * FitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FitRepository,
} from "@peerwheel/services/canvas";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FitRepositoryDdb } from "./fit-repository.ddb.js";

/**
 * FitRepositoryAdapter
 *
 * Implements FitRepository port for infrastructure layer.
 */
export class FitRepositoryAdapter implements FitRepository {
  private readonly ddb: FitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FitRepositoryDdb(this.dynamoClient);
  }

  async getCanvasFit(input: Parameters<FitRepository['getCanvasFit']>[0]): Promise<Awaited<ReturnType<FitRepository['getCanvasFit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCanvasFit(input);
  }

  async updateCanvasFit(input: Parameters<FitRepository['updateCanvasFit']>[0]): Promise<Awaited<ReturnType<FitRepository['updateCanvasFit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCanvasFit(input);
  }
}
