/**
 * Attestations Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const submitIntegrityAttestation_Body = z
  .object({
    result: z.enum(['passed', 'failed', 'hold']),
    phase: z.enum(['pre', 'during', 'post']),
    proofHash: z.string().optional(),
    purposeTag: z.enum([
      'integrity_proof',
      'dispute_evidence',
      'retention_minimised',
    ]),
    sensorTypes: z.array(z.string()).optional(),
    vehicleId: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  submitIntegrityAttestation_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/attestations',
    alias: 'listAttestations',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'result',
        type: 'Query',
        schema: z.enum(['passed', 'failed', 'hold']).optional(),
      },
      {
        name: 'rideId',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  attestationId: z
                    .string()
                    .regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
                  rideId: z.string(),
                  vehicleId: z.string().optional(),
                  result: z.enum(['passed', 'failed', 'hold']),
                  phase: z.enum(['pre', 'during', 'post']),
                  proofHash: z.string().optional(),
                  purposeTag: z.enum([
                    'integrity_proof',
                    'dispute_evidence',
                    'retention_minimised',
                  ]),
                  sensorTypes: z.array(z.string()).optional(),
                  holdCleared: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/attestations/:attestationId',
    alias: 'getAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
            rideId: z.string(),
            vehicleId: z.string().optional(),
            result: z.enum(['passed', 'failed', 'hold']),
            phase: z.enum(['pre', 'during', 'post']),
            proofHash: z.string().optional(),
            purposeTag: z.enum([
              'integrity_proof',
              'dispute_evidence',
              'retention_minimised',
            ]),
            sensorTypes: z.array(z.string()).optional(),
            holdCleared: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/attestations/:attestationId/clear-hold',
    alias: 'clearAttestationHold',
    requestFormat: 'json',
    parameters: [
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
            rideId: z.string(),
            vehicleId: z.string().optional(),
            result: z.enum(['passed', 'failed', 'hold']),
            phase: z.enum(['pre', 'during', 'post']),
            proofHash: z.string().optional(),
            purposeTag: z.enum([
              'integrity_proof',
              'dispute_evidence',
              'retention_minimised',
            ]),
            sensorTypes: z.array(z.string()).optional(),
            holdCleared: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/attestations/:attestationId/keep-hold',
    alias: 'keepAttestationHold',
    requestFormat: 'json',
    parameters: [
      {
        name: 'attestationId',
        type: 'Path',
        schema: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
            rideId: z.string(),
            vehicleId: z.string().optional(),
            result: z.enum(['passed', 'failed', 'hold']),
            phase: z.enum(['pre', 'during', 'post']),
            proofHash: z.string().optional(),
            purposeTag: z.enum([
              'integrity_proof',
              'dispute_evidence',
              'retention_minimised',
            ]),
            sensorTypes: z.array(z.string()).optional(),
            holdCleared: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/rides/:rideId/attestations',
    alias: 'submitIntegrityAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: submitIntegrityAttestation_Body,
      },
      {
        name: 'rideId',
        type: 'Path',
        schema: z.string(),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            attestationId: z.string().regex(/^att_[0-9A-HJKMNP-TV-Z]{26}$/),
            rideId: z.string(),
            vehicleId: z.string().optional(),
            result: z.enum(['passed', 'failed', 'hold']),
            phase: z.enum(['pre', 'during', 'post']),
            proofHash: z.string().optional(),
            purposeTag: z.enum([
              'integrity_proof',
              'dispute_evidence',
              'retention_minimised',
            ]),
            sensorTypes: z.array(z.string()).optional(),
            holdCleared: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
