/**
 * Attestations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestations Domain Module - Composition root
 *
 * DDD: Composition root for attestations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttestationRepositoryAdapter,
  ClearHoldRepositoryAdapter,
  KeepHoldRepositoryAdapter,
} from "@peerwheel/adapters/attestations";
import { getIdGeneratorService } from "@peerwheel/adapters";
import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClearAttestationHold,
  ExecuteGetAttestation,
  ExecuteKeepAttestationHold,
  ExecuteListAttestations,
  ExecuteSubmitIntegrityAttestation,
} from "@peerwheel/services/attestations/usecases";
// Ports (interfaces)
import type {
  AttestationRepository,
  ClearHoldRepository,
  KeepHoldRepository,
} from "@peerwheel/services/attestations/ports";

export interface AttestationsDomainModule {
  repos: {
    attestations: AttestationRepository;
    clearHolds: ClearHoldRepository;
    keepHolds: KeepHoldRepository;
  };
  useCases: {
    attestations: {
      create: ExecuteSubmitIntegrityAttestation;
      get: ExecuteGetAttestation;
      list: ExecuteListAttestations;
    };
    clearHolds: {
      get: ExecuteClearAttestationHold;
    };
    keepHolds: {
      get: ExecuteKeepAttestationHold;
    };
  };
}

export function buildAttestationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AttestationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attestations?: AttestationRepository;
      clearHolds?: ClearHoldRepository;
      keepHolds?: KeepHoldRepository;
    } = {};

    obj.attestations = new AttestationRepositoryAdapter(dynamoClient);
    obj.clearHolds = new ClearHoldRepositoryAdapter(dynamoClient);
    obj.keepHolds = new KeepHoldRepositoryAdapter(dynamoClient);
    return {
      attestations: obj.attestations!,
      clearHolds: obj.clearHolds!,
      keepHolds: obj.keepHolds!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attestations: {
      create: new ExecuteSubmitIntegrityAttestation(executionContext, idGenerator, repos.attestations),
      get: new ExecuteGetAttestation(executionContext, idGenerator, repos.attestations),
      list: new ExecuteListAttestations(executionContext, idGenerator, repos.attestations),
    },
    clearHolds: {
      get: new ExecuteClearAttestationHold(executionContext, idGenerator, repos.clearHolds),
    },
    keepHolds: {
      get: new ExecuteKeepAttestationHold(executionContext, idGenerator, repos.keepHolds),
    },
  };
  return { repos, useCases: useCases as AttestationsDomainModule["useCases"] };
}
