/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./availability-repository.ddb.js";
export * from "./availability-publisher.ddb.js";
export * from "./pull-repository.ddb.js";
export * from "./vehicle-repository.ddb.js";
export * from "./yield-foresight-repository.ddb.js";
export * from "./availability-publisher.adapter.js";
export * from "./availability-repository.adapter.js";
export * from "./pull-repository.adapter.js";
export * from "./vehicle-repository.adapter.js";
export * from "./yield-foresight-repository.adapter.js";
