/**
 * PullRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PullRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PullRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PullRepository,
} from "@peerwheel/services/vehicles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PullRepositoryDdb } from "./pull-repository.ddb.js";

/**
 * PullRepositoryAdapter
 *
 * Implements PullRepository port for infrastructure layer.
 */
export class PullRepositoryAdapter implements PullRepository {
  private readonly ddb: PullRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PullRepositoryDdb(this.dynamoClient);
  }

  async pullAvailability(input: Parameters<PullRepository['pullAvailability']>[0]): Promise<Awaited<ReturnType<PullRepository['pullAvailability']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.pullAvailability(input);
  }
}
