/**
 * VehicleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VehicleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VehicleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VehicleRepository,
} from "@peerwheel/services/vehicles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VehicleRepositoryDdb } from "./vehicle-repository.ddb.js";

/**
 * VehicleRepositoryAdapter
 *
 * Implements VehicleRepository port for infrastructure layer.
 */
export class VehicleRepositoryAdapter implements VehicleRepository {
  private readonly ddb: VehicleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VehicleRepositoryDdb(this.dynamoClient);
  }

  async listVehicles(input: Parameters<VehicleRepository['listVehicles']>[0]): Promise<Awaited<ReturnType<VehicleRepository['listVehicles']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVehicles(input);
  }

  async registerVehicle(input: Parameters<VehicleRepository['registerVehicle']>[0]): Promise<Awaited<ReturnType<VehicleRepository['registerVehicle']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerVehicle(input);
  }

  async getVehicle(input: Parameters<VehicleRepository['getVehicle']>[0]): Promise<Awaited<ReturnType<VehicleRepository['getVehicle']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getVehicle(input);
  }

  async updateVehicle(input: Parameters<VehicleRepository['updateVehicle']>[0]): Promise<Awaited<ReturnType<VehicleRepository['updateVehicle']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateVehicle(input);
  }
}
