/**
 * YieldForesightRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * YieldForesightRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements YieldForesightRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  YieldForesightRepository,
} from "@peerwheel/services/vehicles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { YieldForesightRepositoryDdb } from "./yield-foresight-repository.ddb.js";

/**
 * YieldForesightRepositoryAdapter
 *
 * Implements YieldForesightRepository port for infrastructure layer.
 */
export class YieldForesightRepositoryAdapter implements YieldForesightRepository {
  private readonly ddb: YieldForesightRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new YieldForesightRepositoryDdb(this.dynamoClient);
  }

  async getYieldForesight(input: Parameters<YieldForesightRepository['getYieldForesight']>[0]): Promise<Awaited<ReturnType<YieldForesightRepository['getYieldForesight']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getYieldForesight(input);
  }
}
