/**
 * GetVehicle DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetVehicleParams } from "@peerwheel/core/vehicles";

export function createGetVehicleRequest(overrides: Partial<GetVehicleParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
