/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @peerwheel/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@peerwheel/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@peerwheel/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@peerwheel/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@peerwheel/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@peerwheel/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _attestations from "./attestations/index.js";
import * as _canvas from "./canvas/index.js";
import * as _corridors from "./corridors/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _rides from "./rides/index.js";
import * as _settlements from "./settlements/index.js";
import * as _vehicles from "./vehicles/index.js";

// Export as namespaces
export const _shared = __shared;
export const attestations = _attestations;
export const canvas = _canvas;
export const corridors = _corridors;
export const disputes = _disputes;
export const identity = _identity;
export const rides = _rides;
export const settlements = _settlements;
export const vehicles = _vehicles;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@peerwheel/core"; activity.types.*
//   - Direct exports: import * from "@peerwheel/core/activity/types/index.js"
//   - Direct exports: import * from "@peerwheel/core/activity/repositories/index.js"
//   - Direct exports: import * from "@peerwheel/core/activity/models/index.js"
//   - Direct exports: import * from "@peerwheel/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Attestations Service
export { schemas as AttestationsSchemas } from "./attestations/schemas/attestations.schemas.js";

// Canvas Service
export { schemas as CanvasSchemas } from "./canvas/schemas/canvas.schemas.js";

// Corridors Service
export { schemas as CorridorsSchemas } from "./corridors/schemas/corridors.schemas.js";

// Disputes Service
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Rides Service
export { schemas as RidesSchemas } from "./rides/schemas/rides.schemas.js";

// Settlements Service
export { schemas as SettlementsSchemas } from "./settlements/schemas/settlements.schemas.js";

// Vehicles Service
export { schemas as VehiclesSchemas } from "./vehicles/schemas/vehicles.schemas.js";

