/**
 * GetDispute handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDispute } from "@peerwheel/api-server/domains/disputes/handlers";
import type { DisputesDDDDependencies } from "@peerwheel/api-server/domains/disputes";
import { createDispute as createDisputeEntity } from "@peerwheel/factories/disputes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { DISPUTES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDispute", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DisputesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DisputesDDDDependencies>(
      DISPUTES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDisputeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDispute, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { disputeId: entity.id };

    await getDispute(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDispute.execute).toHaveBeenCalledWith(expect.objectContaining({ disputeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { disputeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDispute, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDispute(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
