/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { corridorRoutes } from "./corridor.routes.js";
export { licensingRoutes } from "./licensing.routes.js";
export { pauseRoutes } from "./pause.routes.js";
export { resumeRoutes } from "./resume.routes.js";
