/**
 * Routes for Licensing
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { updateCorridorLicensing } from "../handlers/licensing.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function licensingRoutes(fastify: FastifyInstance) {
  // PUT /v1/corridors/{corridorId}/licensing (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/corridors/:corridorId/licensing",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { corridorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCorridorsDependenciesForRequest();
        await updateCorridorLicensing(request, reply, deps);
      });
    }
  );


}
