/**
 * Handlers for Attestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AttestationsDomainModule } from "../dependencies/attestations-ddd.dependencies.js";
import type { GetAttestationInput, ListAttestationsInput, SubmitIntegrityAttestationInput } from "@peerwheel/services/attestations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/attestations
 * Operation: listAttestations
 */
export async function listAttestations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], result?: string | string[], rideId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAttestationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.attestations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/rides/{rideId}/attestations
 * Operation: submitIntegrityAttestation
 */
export async function submitIntegrityAttestation(
  request: FastifyRequest<{ Params: { rideId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitIntegrityAttestationInput = {
    rideId: request.params.rideId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attestations.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/attestations/{attestationId}
 * Operation: getAttestation
 */
export async function getAttestation(
  request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAttestationInput = {
    attestationId: request.params.attestationId,
  };
  const result = await deps.useCases.attestations.get.execute(input);
  return reply.code(200).send(result);
}


