/**
 * Handlers for ClearHold
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AttestationsDomainModule } from "../dependencies/attestations-ddd.dependencies.js";
import type { ClearAttestationHoldInput } from "@peerwheel/services/attestations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/attestations/{attestationId}/clear-hold
 * Operation: clearAttestationHold
 */
export async function clearAttestationHold(
  request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ClearAttestationHoldInput = {
    attestationId: request.params.attestationId,
  };
  const result = await deps.useCases.clearHolds.get.execute(input);
  return reply.code(200).send(result);
}


