/**
 * Availability DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Availability DTOs
 *
 * DDD: Application DTOs for Availability use cases.
 */

import type { ListAvailabilityWindowsParams, PublishAvailabilityParams, PublishAvailabilityRequestInput } from "@peerwheel/core/vehicles/types";

export type ListAvailabilityWindowsInput = ListAvailabilityWindowsParams;

export type PublishAvailabilityInput = PublishAvailabilityParams & PublishAvailabilityRequestInput;

export type ListAvailabilityWindowsOutput = {};

export type PublishAvailabilityOutput = {};
