/**
 * Pull DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pull DTOs
 *
 * DDD: Application DTOs for Pull use cases.
 */

import type { PullAvailabilityParams } from "@peerwheel/core/vehicles/types";

export type PullAvailabilityInput = PullAvailabilityParams;

export type PullAvailabilityOutput = {};
