/**
 * Vehicle DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vehicle DTOs
 *
 * DDD: Application DTOs for Vehicle use cases.
 */

import type { GetVehicleParams, ListVehiclesParams, RegisterVehicleRequestInput, UpdateVehicleParams, UpdateVehicleRequestInput } from "@peerwheel/core/vehicles/types";

export type ListVehiclesInput = ListVehiclesParams;

export type RegisterVehicleInput = RegisterVehicleRequestInput;

export type GetVehicleInput = GetVehicleParams;

export type UpdateVehicleInput = UpdateVehicleParams & UpdateVehicleRequestInput;

export type ListVehiclesOutput = {};

export type RegisterVehicleOutput = {};

export type GetVehicleOutput = {};

export type UpdateVehicleOutput = {};
