/**
 * CorridorRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CorridorRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CorridorRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CorridorRepository,
} from "@peerwheel/services/corridors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CorridorRepositoryDdb } from "./corridor-repository.ddb.js";

/**
 * CorridorRepositoryAdapter
 *
 * Implements CorridorRepository port for infrastructure layer.
 */
export class CorridorRepositoryAdapter implements CorridorRepository {
  private readonly ddb: CorridorRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CorridorRepositoryDdb(this.dynamoClient);
  }

  async listCorridors(input: Parameters<CorridorRepository['listCorridors']>[0]): Promise<Awaited<ReturnType<CorridorRepository['listCorridors']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCorridors(input);
  }

  async getCorridor(input: Parameters<CorridorRepository['getCorridor']>[0]): Promise<Awaited<ReturnType<CorridorRepository['getCorridor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCorridor(input);
  }
}
