/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./corridor-repository.ddb.js";
export * from "./licensing-repository.ddb.js";
export * from "./pause-repository.ddb.js";
export * from "./resume-repository.ddb.js";
export * from "./corridor-repository.adapter.js";
export * from "./licensing-repository.adapter.js";
export * from "./pause-repository.adapter.js";
export * from "./resume-repository.adapter.js";
