/**
 * LicensingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicensingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LicensingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LicensingRepository,
} from "@peerwheel/services/corridors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LicensingRepositoryDdb } from "./licensing-repository.ddb.js";

/**
 * LicensingRepositoryAdapter
 *
 * Implements LicensingRepository port for infrastructure layer.
 */
export class LicensingRepositoryAdapter implements LicensingRepository {
  private readonly ddb: LicensingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LicensingRepositoryDdb(this.dynamoClient);
  }

  async updateCorridorLicensing(input: Parameters<LicensingRepository['updateCorridorLicensing']>[0]): Promise<Awaited<ReturnType<LicensingRepository['updateCorridorLicensing']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCorridorLicensing(input);
  }
}
