/**
 * ResumeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ResumeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ResumeRepository,
} from "@peerwheel/services/corridors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ResumeRepositoryDdb } from "./resume-repository.ddb.js";

/**
 * ResumeRepositoryAdapter
 *
 * Implements ResumeRepository port for infrastructure layer.
 */
export class ResumeRepositoryAdapter implements ResumeRepository {
  private readonly ddb: ResumeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ResumeRepositoryDdb(this.dynamoClient);
  }

  async resumeCorridor(input: Parameters<ResumeRepository['resumeCorridor']>[0]): Promise<Awaited<ReturnType<ResumeRepository['resumeCorridor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.resumeCorridor(input);
  }
}
