/**
 * Routes for KeepHold
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { keepAttestationHold } from "../handlers/keep-hold.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function keepHoldRoutes(fastify: FastifyInstance) {
  // POST /v1/attestations/{attestationId}/keep-hold (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/attestations/:attestationId/keep-hold",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { attestationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAttestationsDependenciesForRequest();
        await keepAttestationHold(request, reply, deps);
      });
    }
  );


}
