/**
 * GetSettlement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSettlement } from "@peerwheel/api-server/domains/settlements/handlers";
import type { SettlementsDDDDependencies } from "@peerwheel/api-server/domains/settlements";
import { createSettlement as createSettlementEntity } from "@peerwheel/factories/settlements";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { SETTLEMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSettlement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SettlementsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SettlementsDDDDependencies>(
      SETTLEMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSettlementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSettlement, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { settlementId: entity.id };

    await getSettlement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSettlement.execute).toHaveBeenCalledWith(expect.objectContaining({ settlementId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { settlementId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSettlement, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSettlement(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
