/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { completeRoutes } from "./complete.routes.js";
export { matchRoutes } from "./match.routes.js";
export { refuseRoutes } from "./refuse.routes.js";
export { rideRoutes } from "./ride.routes.js";
