/**
 * Routes for Ride
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getRide, listRides, requestRide } from "../handlers/ride.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function rideRoutes(fastify: FastifyInstance) {
  // GET /v1/rides (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/rides",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRidesDependenciesForRequest();
        await listRides(request, reply, deps);
      });
    }
  );


  // POST /v1/rides (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/rides",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRidesDependenciesForRequest();
        await requestRide(request, reply, deps);
      });
    }
  );


  // GET /v1/rides/{rideId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/rides/:rideId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { rideId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRidesDependenciesForRequest();
        await getRide(request, reply, deps);
      });
    }
  );


}
