/**
 * Vehicle Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { VehicleEntity } from "@peerwheel/core/vehicles/models/index.js";
import { vehiclesSchemas } from "@peerwheel/core/vehicles";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "veh";

export function createVehicle(overrides: Partial<VehicleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    ownerId: overrides.ownerId ?? faker.string.uuid(),
    status: overrides.status ?? "active",
    vehicleId: overrides.vehicleId ?? `veh_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return vehiclesSchemas.Vehicle.parse(raw);
}

export function vehicleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createVehicle(overrides));
}
