/**
 * Corridor Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CorridorEntity } from "@peerwheel/core/corridors/models/index.js";
import { corridorsSchemas } from "@peerwheel/core/corridors";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cor";

export function createCorridor(overrides: Partial<CorridorEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    corridorId: overrides.corridorId ?? `cor_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "active",
    ...overrides,
  };

  return corridorsSchemas.Corridor.parse(raw);
}

export function corridorBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCorridor(overrides));
}
