/**
 * GetYieldForesight handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getYieldForesight } from "@peerwheel/api-server/domains/vehicles/handlers";
import type { VehiclesDDDDependencies } from "@peerwheel/api-server/domains/vehicles";
import { createYieldForesight as createYieldForesightEntity } from "@peerwheel/factories/vehicles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { VEHICLES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetYieldForesight", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VehiclesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VehiclesDDDDependencies>(
      VEHICLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createYieldForesightEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetYieldForesight, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { vehicleId: entity.id };

    await getYieldForesight(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetYieldForesight.execute).toHaveBeenCalledWith(expect.objectContaining({ vehicleId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { vehicleId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetYieldForesight, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getYieldForesight(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
