/**
 * RefuseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefuseRepository Port
 *
 * DDD: Application port for refuserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RefuseRideInput, RefuseRideOutput } from "../dto/refuse.dto";
export interface RefuseRepository {
  refuseRide(input: RefuseRideInput): Promise<RefuseRideOutput>;
}

export type { RefuseRideInput, RefuseRideOutput } from "../dto/refuse.dto";
