/**
 * Canvas DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Canvas Domain Module - Composition root
 *
 * DDD: Composition root for canvas domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FitRepositoryAdapter,
} from "@peerwheel/adapters/canvas";
import { getIdGeneratorService } from "@peerwheel/adapters";
import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetCanvasFit,
  ExecuteUpdateCanvasFit,
} from "@peerwheel/services/canvas/usecases";
// Ports (interfaces)
import type {
  FitRepository,
} from "@peerwheel/services/canvas/ports";

export interface CanvasDomainModule {
  repos: {
    fits: FitRepository;
  };
  useCases: {
    fits: {
      get: ExecuteGetCanvasFit;
      update: ExecuteUpdateCanvasFit;
    };
  };
}

export function buildCanvasDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CanvasDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      fits?: FitRepository;
    } = {};

    obj.fits = new FitRepositoryAdapter(dynamoClient);
    return {
      fits: obj.fits!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    fits: {
      get: new ExecuteGetCanvasFit(executionContext, idGenerator, repos.fits),
      update: new ExecuteUpdateCanvasFit(executionContext, idGenerator, repos.fits),
    },
  };
  return { repos, useCases: useCases as CanvasDomainModule["useCases"] };
}
