/**
 * GetCorridor handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCorridor } from "@peerwheel/api-server/domains/corridors/handlers";
import type { CorridorsDDDDependencies } from "@peerwheel/api-server/domains/corridors";
import { createCorridor as createCorridorEntity } from "@peerwheel/factories/corridors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { CORRIDORS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCorridor", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CorridorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CorridorsDDDDependencies>(
      CORRIDORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createCorridorEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCorridor, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { corridorId: entity.id };

    await getCorridor(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCorridor.execute).toHaveBeenCalledWith(expect.objectContaining({ corridorId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { corridorId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCorridor, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCorridor(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
