/**
 * Ride Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RideEntity } from "@peerwheel/core/rides/models/index.js";
import { ridesSchemas } from "@peerwheel/core/rides";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rid";

export function createRide(overrides: Partial<RideEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    channel: overrides.channel ?? "app",
    rideId: overrides.rideId ?? `rid_${ulid().toLowerCase()}`,
    status: overrides.status ?? "requested",
    ...overrides,
  };

  return ridesSchemas.Ride.parse(raw);
}

export function rideBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRide(overrides));
}
