/**
 * RetryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RetryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RetryRepository,
} from "@peerwheel/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RetryRepositoryDdb } from "./retry-repository.ddb.js";

/**
 * RetryRepositoryAdapter
 *
 * Implements RetryRepository port for infrastructure layer.
 */
export class RetryRepositoryAdapter implements RetryRepository {
  private readonly ddb: RetryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RetryRepositoryDdb(this.dynamoClient);
  }

  async retrySettlement(input: Parameters<RetryRepository['retrySettlement']>[0]): Promise<Awaited<ReturnType<RetryRepository['retrySettlement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.retrySettlement(input);
  }
}
