/**
 * SettlementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettlementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SettlementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SettlementRepository,
} from "@peerwheel/services/settlements";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SettlementRepositoryDdb } from "./settlement-repository.ddb.js";

/**
 * SettlementRepositoryAdapter
 *
 * Implements SettlementRepository port for infrastructure layer.
 */
export class SettlementRepositoryAdapter implements SettlementRepository {
  private readonly ddb: SettlementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SettlementRepositoryDdb(this.dynamoClient);
  }

  async listSettlements(input: Parameters<SettlementRepository['listSettlements']>[0]): Promise<Awaited<ReturnType<SettlementRepository['listSettlements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSettlements(input);
  }

  async getSettlement(input: Parameters<SettlementRepository['getSettlement']>[0]): Promise<Awaited<ReturnType<SettlementRepository['getSettlement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSettlement(input);
  }
}
