/**
 * PublishAvailability handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { publishAvailability } from "@peerwheel/api-server/domains/vehicles/handlers";
import type { VehiclesDDDDependencies } from "@peerwheel/api-server/domains/vehicles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { VEHICLES_USE_CASES } from "../__factories__/use-cases.js";

describe("PublishAvailability", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VehiclesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VehiclesDDDDependencies>(
      VEHICLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePublishAvailability, "execute").mockResolvedValue(useCaseResult);

    await publishAvailability(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePublishAvailability.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
