/**
 * GetCorridor DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCorridorParams } from "@peerwheel/core/corridors";

export function createGetCorridorRequest(overrides: Partial<GetCorridorParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
