/**
 * Routes for Fit
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCanvasFit, updateCanvasFit } from "../handlers/fit.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function fitRoutes(fastify: FastifyInstance) {
  // GET /v1/canvas/fits (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/canvas/fits",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCanvasDependenciesForRequest();
        await getCanvasFit(request, reply, deps);
      });
    }
  );


  // PUT /v1/canvas/fits (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/canvas/fits",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCanvasDependenciesForRequest();
        await updateCanvasFit(request, reply, deps);
      });
    }
  );


}
