/**
 * Corridors DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Corridors Domain Module - Composition root
 *
 * DDD: Composition root for corridors domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CorridorRepositoryAdapter,
  LicensingRepositoryAdapter,
  PauseRepositoryAdapter,
  ResumeRepositoryAdapter,
} from "@peerwheel/adapters/corridors";
import { getIdGeneratorService } from "@peerwheel/adapters";
import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetCorridor,
  ExecuteListCorridors,
  ExecutePauseCorridor,
  ExecuteResumeCorridor,
  ExecuteUpdateCorridorLicensing,
} from "@peerwheel/services/corridors/usecases";
// Ports (interfaces)
import type {
  CorridorRepository,
  LicensingRepository,
  PauseRepository,
  ResumeRepository,
} from "@peerwheel/services/corridors/ports";

export interface CorridorsDomainModule {
  repos: {
    corridors: CorridorRepository;
    licensings: LicensingRepository;
    pauses: PauseRepository;
    resumes: ResumeRepository;
  };
  useCases: {
    corridors: {
      get: ExecuteGetCorridor;
      list: ExecuteListCorridors;
    };
    licensings: {
      update: ExecuteUpdateCorridorLicensing;
    };
    pauses: {
      get: ExecutePauseCorridor;
    };
    resumes: {
      get: ExecuteResumeCorridor;
    };
  };
}

export function buildCorridorsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CorridorsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      corridors?: CorridorRepository;
      licensings?: LicensingRepository;
      pauses?: PauseRepository;
      resumes?: ResumeRepository;
    } = {};

    obj.corridors = new CorridorRepositoryAdapter(dynamoClient);
    obj.licensings = new LicensingRepositoryAdapter(dynamoClient);
    obj.pauses = new PauseRepositoryAdapter(dynamoClient);
    obj.resumes = new ResumeRepositoryAdapter(dynamoClient);
    return {
      corridors: obj.corridors!,
      licensings: obj.licensings!,
      pauses: obj.pauses!,
      resumes: obj.resumes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    corridors: {
      get: new ExecuteGetCorridor(executionContext, idGenerator, repos.corridors),
      list: new ExecuteListCorridors(executionContext, idGenerator, repos.corridors),
    },
    licensings: {
      update: new ExecuteUpdateCorridorLicensing(executionContext, idGenerator, repos.licensings),
    },
    pauses: {
      get: new ExecutePauseCorridor(executionContext, idGenerator, repos.pauses),
    },
    resumes: {
      get: new ExecuteResumeCorridor(executionContext, idGenerator, repos.resumes),
    },
  };
  return { repos, useCases: useCases as CorridorsDomainModule["useCases"] };
}
