/**
 * ExecutePauseCorridor - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePauseCorridor Use Case
 *
 * DDD: Application use case for get Pause.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PauseCorridorInput, PauseCorridorOutput } from "../dto/pause.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { PauseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePauseCorridor {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pause: PauseRepository
  ) {}

  async execute(input: PauseCorridorInput): Promise<PauseCorridorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.corId();

    // All field names extracted from OpenAPI spec: reason, vehicleClasses
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).corridorId) {
      throw new ValidationError("corridorId is required");
    }
    const corridorId = (input as any).corridorId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.pause.pauseCorridor({ corridorId: corridorId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${corridorId}`);
    }

    return entity as PauseCorridorOutput;
  }
}
