/**
 * ExecuteListCorridors - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCorridors Use Case
 *
 * DDD: Application use case for list Corridor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCorridorsInput, ListCorridorsOutput } from "../dto/corridor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { CorridorRepository } from "../ports";

export class ExecuteListCorridors {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly corridor: CorridorRepository
  ) {}

  async execute(input: ListCorridorsInput): Promise<ListCorridorsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.corId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.corridor.listCorridors({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCorridorsOutput;
  }
}
