/**
 * Fit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: canvas
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fit DTOs
 *
 * DDD: Application DTOs for Fit use cases.
 */

import type { UpdateCanvasFitRequestInput } from "@peerwheel/core/canvas/types";

export type GetCanvasFitInput = {};

export type UpdateCanvasFitInput = UpdateCanvasFitRequestInput;

export type GetCanvasFitOutput = {};

export type UpdateCanvasFitOutput = {};
