/**
 * CreateClearHold DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ClearAttestationHoldParams } from "@peerwheel/core/attestations";

export function createCreateClearHoldRequest(overrides: Partial<ClearAttestationHoldParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
