/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@peerwheel/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@peerwheel/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@peerwheel/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _attestations from "./attestations/index.js";
import * as _canvas from "./canvas/index.js";
import * as _corridors from "./corridors/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _rides from "./rides/index.js";
import * as _settlements from "./settlements/index.js";
import * as _vehicles from "./vehicles/index.js";

// Export as namespaces
export const attestations = _attestations;
export const canvas = _canvas;
export const corridors = _corridors;
export const disputes = _disputes;
export const identity = _identity;
export const rides = _rides;
export const settlements = _settlements;
export const vehicles = _vehicles;
