/**
 * GetRide handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRide } from "@peerwheel/api-server/domains/rides/handlers";
import type { RidesDDDDependencies } from "@peerwheel/api-server/domains/rides";
import { createRide as createRideEntity } from "@peerwheel/factories/rides";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@peerwheel/tests/shared";
import { RIDES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRide", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RidesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RidesDDDDependencies>(
      RIDES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRideEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRide, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { rideId: entity.id };

    await getRide(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRide.execute).toHaveBeenCalledWith(expect.objectContaining({ rideId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { rideId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRide, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRide(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
