/**
 * Handlers for Availability
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VehiclesDomainModule } from "../dependencies/vehicles-ddd.dependencies.js";
import type { ListAvailabilityWindowsInput, PublishAvailabilityInput } from "@peerwheel/services/vehicles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/vehicles/{vehicleId}/availability
 * Operation: listAvailabilityWindows
 */
export async function listAvailabilityWindows(
  request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: { cursor?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAvailabilityWindowsInput = {
    vehicleId: request.params.vehicleId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.availabilities.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/vehicles/{vehicleId}/availability
 * Operation: publishAvailability
 */
export async function publishAvailability(
  request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PublishAvailabilityInput = {
    vehicleId: request.params.vehicleId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.availabilities.get.execute(input);
  return reply.code(201).send(result);
}


