/**
 * Handlers for Vehicle
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VehiclesDomainModule } from "../dependencies/vehicles-ddd.dependencies.js";
import type { GetVehicleInput, ListVehiclesInput, RegisterVehicleInput, UpdateVehicleInput } from "@peerwheel/services/vehicles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/vehicles
 * Operation: listVehicles
 */
export async function listVehicles(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], status?: string | string[], ownerId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListVehiclesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.vehicles.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/vehicles
 * Operation: registerVehicle
 */
export async function registerVehicle(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterVehicleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vehicles.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/vehicles/{vehicleId}
 * Operation: getVehicle
 */
export async function getVehicle(
  request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetVehicleInput = {
    vehicleId: request.params.vehicleId,
  };
  const result = await deps.useCases.vehicles.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/vehicles/{vehicleId}
 * Operation: updateVehicle
 */
export async function updateVehicle(
  request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateVehicleInput = {
    vehicleId: request.params.vehicleId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vehicles.update.execute(input);
  return reply.code(200).send(result);
}


