/**
 * Handlers for YieldForesight
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vehicles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VehiclesDomainModule } from "../dependencies/vehicles-ddd.dependencies.js";
import type { GetYieldForesightInput } from "@peerwheel/services/vehicles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/vehicles/{vehicleId}/yield-foresight
 * Operation: getYieldForesight
 */
export async function getYieldForesight(
  request: FastifyRequest<{ Params: { vehicleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VehiclesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetYieldForesightInput = {
    vehicleId: request.params.vehicleId,
  };
  const result = await deps.useCases.yieldForesights.get.execute(input);
  return reply.code(200).send(result);
}


