/**
 * Repository interface for Ride
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RideEntity
} from "../models/ride.entity.js";
import type {
  ListRidesParams,
  Ride
} from "../types/index.js";
/**
 * RideRepository Interface
 */
export interface RideRepository extends CreateReadRepository<RideEntity, Ride, string, ListRidesParams> {

}
