/**
 * Ride Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/rides.openapi.types.js";
import { schemas } from "../schemas/rides.schemas.js";

/**
 * Entity: RideEntity
 * Description: Represents the Ride domain model.
 * Source: schemas.Ride
 * Type: Domain Entity (API)
 */
export const RideEntitySchema = schemas.Ride;
export type RideEntity = components["schemas"]["Ride"];
