/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./corridor.handlers.js";
export * from "./licensing.handlers.js";
export * from "./pause.handlers.js";
export * from "./resume.handlers.js";
