/**
 * Disputes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disputes Domain Module - Composition root
 *
 * DDD: Composition root for disputes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisputeRepositoryAdapter,
  ExportRepositoryAdapter,
  ExtendRepositoryAdapter,
  ResolveRepositoryAdapter,
} from "@peerwheel/adapters/disputes";
import { getIdGeneratorService } from "@peerwheel/adapters";
import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExportDisputeCasePack,
  ExecuteExtendDispute,
  ExecuteGetDispute,
  ExecuteListDisputes,
  ExecuteOpenDispute,
  ExecuteResolveDispute,
} from "@peerwheel/services/disputes/usecases";
// Ports (interfaces)
import type {
  DisputeRepository,
  ExportRepository,
  ExtendRepository,
  ResolveRepository,
} from "@peerwheel/services/disputes/ports";

export interface DisputesDomainModule {
  repos: {
    disputes: DisputeRepository;
    exports: ExportRepository;
    extends: ExtendRepository;
    resolves: ResolveRepository;
  };
  useCases: {
    disputes: {
      get: ExecuteGetDispute;
      list: ExecuteListDisputes;
    };
    exports: {
      list: ExecuteExportDisputeCasePack;
    };
    extends: {
      get: ExecuteExtendDispute;
    };
    resolves: {
      get: ExecuteResolveDispute;
    };
  };
}

export function buildDisputesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DisputesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disputes?: DisputeRepository;
      exports?: ExportRepository;
      extends?: ExtendRepository;
      resolves?: ResolveRepository;
    } = {};

    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    obj.extends = new ExtendRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    return {
      disputes: obj.disputes!,
      exports: obj.exports!,
      extends: obj.extends!,
      resolves: obj.resolves!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disputes: {
      get: new ExecuteGetDispute(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListDisputes(executionContext, idGenerator, repos.disputes),
    },
    exports: {
      list: new ExecuteExportDisputeCasePack(executionContext, idGenerator, repos.exports),
    },
    extends: {
      get: new ExecuteExtendDispute(executionContext, idGenerator, repos.extends),
    },
    resolves: {
      get: new ExecuteResolveDispute(executionContext, idGenerator, repos.resolves),
    },
  };
  return { repos, useCases: useCases as DisputesDomainModule["useCases"] };
}
