/**
 * ExecuteListSettlements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSettlements Use Case
 *
 * DDD: Application use case for list Settlement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSettlementsInput, ListSettlementsOutput } from "../dto/settlement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { SettlementRepository } from "../ports";

export class ExecuteListSettlements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly settlement: SettlementRepository
  ) {}

  async execute(input: ListSettlementsInput): Promise<ListSettlementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.settlement.listSettlements({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSettlementsOutput;
  }
}
