/**
 * ExecuteGetSettlement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSettlement Use Case
 *
 * DDD: Application use case for get Settlement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSettlementInput, GetSettlementOutput } from "../dto/settlement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { SettlementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSettlement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly settlement: SettlementRepository
  ) {}

  async execute(input: GetSettlementInput): Promise<GetSettlementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).settlementId) {
      throw new ValidationError("settlementId is required");
    }
    const settlementId = (input as any).settlementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.settlement.getSettlement({ settlementId: settlementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${settlementId}`);
    }

    return entity as GetSettlementOutput;
  }
}
