/**
 * ExecuteRetrySettlement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRetrySettlement Use Case
 *
 * DDD: Application use case for get Retry.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RetrySettlementInput, RetrySettlementOutput } from "../dto/retry.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { RetryRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRetrySettlement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly retry: RetryRepository
  ) {}

  async execute(input: RetrySettlementInput): Promise<RetrySettlementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: rail
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).settlementId) {
      throw new ValidationError("settlementId is required");
    }
    const settlementId = (input as any).settlementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.retry.retrySettlement({ settlementId: settlementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${settlementId}`);
    }

    return entity as RetrySettlementOutput;
  }
}
