/**
 * ExecuteExecuteSettlement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExecuteSettlement Use Case
 *
 * DDD: Application use case for create Execute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExecuteSettlementInput, ExecuteSettlementOutput } from "../dto/execute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@peerwheel/services/_shared/index.js";
import type { ExecuteRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteExecuteSettlement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly executeRepository: ExecuteRepository
  ) {}

  async execute(input: ExecuteSettlementInput): Promise<ExecuteSettlementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: rail
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (settlements domain)
    const entityId = this.idGenerator.stlId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.executeRepository.executeSettlement({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ExecuteSettlementOutput;
  }
}
