/**
 * ListExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ExportDisputeCasePackParams } from "@peerwheel/core/disputes";

export function createListExportRequest(overrides: Partial<ExportDisputeCasePackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
