/**
 * ExtendRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExtendRepository Port
 *
 * DDD: Application port for extendrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExtendDisputeInput, ExtendDisputeOutput } from "../dto/extend.dto";
export interface ExtendRepository {
  extendDispute(input: ExtendDisputeInput): Promise<ExtendDisputeOutput>;
}

export type { ExtendDisputeInput, ExtendDisputeOutput } from "../dto/extend.dto";
