/**
 * KeepHoldRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeepHoldRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KeepHoldRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KeepHoldRepository,
} from "@peerwheel/services/attestations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KeepHoldRepositoryDdb } from "./keep-hold-repository.ddb.js";

/**
 * KeepHoldRepositoryAdapter
 *
 * Implements KeepHoldRepository port for infrastructure layer.
 */
export class KeepHoldRepositoryAdapter implements KeepHoldRepository {
  private readonly ddb: KeepHoldRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KeepHoldRepositoryDdb(this.dynamoClient);
  }

  async keepAttestationHold(input: Parameters<KeepHoldRepository['keepAttestationHold']>[0]): Promise<Awaited<ReturnType<KeepHoldRepository['keepAttestationHold']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.keepAttestationHold(input);
  }
}
