/**
 * Match DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Match DTOs
 *
 * DDD: Application DTOs for Match use cases.
 */

import type { MatchRideParams, MatchRideRequestInput } from "@peerwheel/core/rides/types";

export type MatchRideInput = MatchRideParams & MatchRideRequestInput;

export type MatchRideOutput = {};
