/**
 * Refuse DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Refuse DTOs
 *
 * DDD: Application DTOs for Refuse use cases.
 */

import type { RefuseRideParams } from "@peerwheel/core/rides/types";

export type RefuseRideInput = RefuseRideParams;

export type RefuseRideOutput = {};
