/**
 * Ride DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Ride DTOs
 *
 * DDD: Application DTOs for Ride use cases.
 */

import type { GetRideParams, ListRidesParams, RequestRideRequestInput } from "@peerwheel/core/rides/types";

export type ListRidesInput = ListRidesParams;

export type RequestRideInput = RequestRideRequestInput;

export type GetRideInput = GetRideParams;

export type ListRidesOutput = {};

export type RequestRideOutput = {};

export type GetRideOutput = {};
