/**
 * Rides DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Rides Domain Module - Composition root
 *
 * DDD: Composition root for rides domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CompleteRepositoryAdapter,
  MatchRepositoryAdapter,
  RefuseRepositoryAdapter,
  RideRepositoryAdapter,
} from "@peerwheel/adapters/rides";
import { getIdGeneratorService } from "@peerwheel/adapters";
import type { AdapterDynamoDBClient } from "@peerwheel/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCompleteRide,
  ExecuteGetRide,
  ExecuteListRides,
  ExecuteMatchRide,
  ExecuteRefuseRide,
  ExecuteRequestRide,
} from "@peerwheel/services/rides/usecases";
// Ports (interfaces)
import type {
  CompleteRepository,
  MatchRepository,
  RefuseRepository,
  RideRepository,
} from "@peerwheel/services/rides/ports";

export interface RidesDomainModule {
  repos: {
    completes: CompleteRepository;
    matches: MatchRepository;
    refuses: RefuseRepository;
    rides: RideRepository;
  };
  useCases: {
    completes: {
      create: ExecuteCompleteRide;
    };
    matches: {
      get: ExecuteMatchRide;
    };
    refuses: {
      get: ExecuteRefuseRide;
    };
    rides: {
      get: ExecuteGetRide;
      list: ExecuteListRides;
    };
  };
}

export function buildRidesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RidesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      completes?: CompleteRepository;
      matches?: MatchRepository;
      refuses?: RefuseRepository;
      rides?: RideRepository;
    } = {};

    obj.completes = new CompleteRepositoryAdapter(dynamoClient);
    obj.matches = new MatchRepositoryAdapter(dynamoClient);
    obj.refuses = new RefuseRepositoryAdapter(dynamoClient);
    obj.rides = new RideRepositoryAdapter(dynamoClient);
    return {
      completes: obj.completes!,
      matches: obj.matches!,
      refuses: obj.refuses!,
      rides: obj.rides!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    completes: {
      create: new ExecuteCompleteRide(executionContext, idGenerator, repos.completes),
    },
    matches: {
      get: new ExecuteMatchRide(executionContext, idGenerator, repos.matches),
    },
    refuses: {
      get: new ExecuteRefuseRide(executionContext, idGenerator, repos.refuses),
    },
    rides: {
      get: new ExecuteGetRide(executionContext, idGenerator, repos.rides),
      list: new ExecuteListRides(executionContext, idGenerator, repos.rides),
    },
  };
  return { repos, useCases: useCases as RidesDomainModule["useCases"] };
}
