/**
 * Corridors Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: corridors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const pauseCorridor_Body = z
  .object({
    vehicleClasses: z.array(
      z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other'])
    ),
    reason: z.string(),
  })
  .partial()
  .passthrough();
const resumeCorridor_Body = z
  .object({
    vehicleClasses: z.array(
      z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other'])
    ),
  })
  .partial()
  .passthrough();
const updateCorridorLicensing_Body = z
  .object({ licensingTags: z.array(z.string()) })
  .passthrough();

export const schemas: any = {
  pauseCorridor_Body,
  resumeCorridor_Body,
  updateCorridorLicensing_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/corridors',
    alias: 'listCorridors',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['active', 'paused']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  corridorId: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  metro: z.string().optional(),
                  status: z.enum(['active', 'paused']),
                  pausedVehicleClasses: z
                    .array(
                      z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other'])
                    )
                    .optional(),
                  licensingTags: z.array(z.string()).optional(),
                  pauseReason: z.string().optional(),
                  pausedAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/corridors/:corridorId',
    alias: 'getCorridor',
    requestFormat: 'json',
    parameters: [
      {
        name: 'corridorId',
        type: 'Path',
        schema: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            corridorId: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            metro: z.string().optional(),
            status: z.enum(['active', 'paused']),
            pausedVehicleClasses: z
              .array(z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other']))
              .optional(),
            licensingTags: z.array(z.string()).optional(),
            pauseReason: z.string().optional(),
            pausedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/corridors/:corridorId/licensing',
    alias: 'updateCorridorLicensing',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateCorridorLicensing_Body,
      },
      {
        name: 'corridorId',
        type: 'Path',
        schema: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            corridorId: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            metro: z.string().optional(),
            status: z.enum(['active', 'paused']),
            pausedVehicleClasses: z
              .array(z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other']))
              .optional(),
            licensingTags: z.array(z.string()).optional(),
            pauseReason: z.string().optional(),
            pausedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/corridors/:corridorId/pause',
    alias: 'pauseCorridor',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: pauseCorridor_Body.optional(),
      },
      {
        name: 'corridorId',
        type: 'Path',
        schema: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            corridorId: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            metro: z.string().optional(),
            status: z.enum(['active', 'paused']),
            pausedVehicleClasses: z
              .array(z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other']))
              .optional(),
            licensingTags: z.array(z.string()).optional(),
            pauseReason: z.string().optional(),
            pausedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/corridors/:corridorId/resume',
    alias: 'resumeCorridor',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: resumeCorridor_Body.optional(),
      },
      {
        name: 'corridorId',
        type: 'Path',
        schema: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            corridorId: z.string().regex(/^cor_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            metro: z.string().optional(),
            status: z.enum(['active', 'paused']),
            pausedVehicleClasses: z
              .array(z.enum(['sedan_av', 'van_av', 'shared_shuttle', 'other']))
              .optional(),
            licensingTags: z.array(z.string()).optional(),
            pauseReason: z.string().optional(),
            pausedAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
