/**
 * GetRide DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rides
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRideParams } from "@peerwheel/core/rides";

export function createGetRideRequest(overrides: Partial<GetRideParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
